flags: {}
extra-package-dbs: []
packages:
- '.'
# - llvm-general-pure
# - llvm-general
extra-deps:
- unordered-containers-0.2.9.0
- llvm-hs-7.0.1
- llvm-hs-pure-7.0.0

resolver: lts-12.14
